# Generated by Django 5.2.8 on 2025-11-19 19:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_vaultfile_aes_key_encrypted_fernet_key'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CloudUploadLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('s3_key', models.CharField(help_text='S3 object key/path', max_length=500)),
                ('s3_url', models.URLField(help_text='Full S3 URL of the uploaded file', max_length=1000)),
                ('file_size', models.BigIntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('content_type', models.CharField(blank=True, max_length=255, null=True)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cloud_uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cloud Upload Log',
                'verbose_name_plural': 'Cloud Upload Logs',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
